---
version: "3.8"

networks:
  services-network:
    ipam:
      config:
        - subnet: "$SERVICES_SUBNET"

services:
  caddy-proxy:
    extends:
      file: "${SERVICES_PATH}/caddy-proxy.yml"
      service: caddy-proxy
  piwigo:
    extends:
      file: "${SERVICES_PATH}/piwigo.yml"
      service: piwigo_web
  piwigo-db:
    extends:
      file: "${SERVICES_PATH}/piwigo.yml"
      service: piwigo_db
  drawio:
    extends:
      file: "${SERVICES_PATH}/drawio.yml"
      service: drawio
  gitlab:
    extends:
      file: "${SERVICES_PATH}/gitlab.yml"
      service: gitlab
  taiga-db:
    extends:
      file: "${SERVICES_PATH}/taiga.yml"
      service: taiga-db
  taiga-back:
    extends:
      file: "${SERVICES_PATH}/taiga.yml"
      service: taiga-back
  taiga-async:
    extends:
      file: "${SERVICES_PATH}/taiga.yml"
      service: taiga-async
  taiga-async-rabbitmq:
    extends:
      file: "${SERVICES_PATH}/taiga.yml"
      service: taiga-async-rabbitmq
  taiga-front:
    extends:
      file: "${SERVICES_PATH}/taiga.yml"
      service: taiga-front
  taiga-events:
    extends:
      file: "${SERVICES_PATH}/taiga.yml"
      service: taiga-events
  taiga-events-rabbitmq:
    extends:
      file: "${SERVICES_PATH}/taiga.yml"
      service: taiga-events-rabbitmq
  taiga-protected:
    extends:
      file: "${SERVICES_PATH}/taiga.yml"
      service: taiga-protected
  taiga-gateway:
    extends:
      file: "${SERVICES_PATH}/taiga.yml"
      service: taiga-gateway
  navidrome:
    extends:
      file: "${SERVICES_PATH}/navidrome.yml"
      service: navidrome
  navi-dl:
    extends:
      file: "${SERVICES_PATH}/navi-downloader.yml"
      service: navi-dl
  docker-registry:
    extends:
      file: "${SERVICES_PATH}/docker-registry.yml"
      service: docker-registry


volumes:
  taiga-static-data:
  taiga-media-data:
  taiga-db-data:
  taiga-async-rabbitmq-data:
  taiga-events-rabbitmq-data:
  docker-registry-data:
  navidata:
  music:
  ca:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${CONFIG_FOLDER}/ca/
  navi-dl-conf:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${CONFIG_FOLDER}/navi-dl/
  music-test:
