---
version: "3.3"

networks:
  services-network:
    ipam:
      config:
        - subnet: "$SERVICES_SUBNET"

services:
  piwigo:
    extends:
      file: "${SERVICES_PATH}/piwigo.yml"
      service: piwigo_web
  piwigo-db:
    extends:
      file: "${SERVICES_PATH}/piwigo.yml"
      service: piwigo_db 
