services:
  piwigo_web:
    extends:
      file: "${TEMPLATE_FOLDER}/${WEB_TEMPLATE}.yml"
      service: "${WEB_TEMPLATE}"
    image: "${PIWIGO_IMAGE}"
    container_name: "${PIWIGO_HOSTNAME}-${WEB_NAME}"
    hostname: "${PIWIGO_HOSTNAME}-${WEB_NAME}"
    volumes:
      - "${VOLUME_FOLDER}/${PIWIGO_HOSTNAME}/config:/config"
      - "${VOLUME_FOLDER}/${PIWIGO_HOSTNAME}/gallery:/gallery"
    networks:
      services-network:
        ipv4_address: "${PIWIGO_IP}"
  piwigo_db:
    extends:
      file: "${TEMPLATE_FOLDER}/${DB_TEMPLATE}.yml"
      service: "${DB_TEMPLATE}"
    image: "${MYSQL_IMAGE}"
    container_name: "${PIWIGO_HOSTNAME}-${DB_NAME}"
    hostname: "${PIWIGO_HOSTNAME}-${DB_NAME}"
    environment:
      MYSQL_ROOT_PASSWORD: "${PIWIGO_DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${PIWIGO_DB}"
      MYSQL_USER: "${PIWIGO_DB_USER}"
      MYSQL_PASSWORD: "${PIWIGO_DB_PASSWORD}"
    volumes: 
      - "${VOLUME_FOLDER}/${PIWIGO_HOSTNAME}/${DB_NAME}:/var/lib/mysql"
