version: "3.5"

x-environment:
  &default-back-environment
  # Database settings
  POSTGRES_DB: taiga
  POSTGRES_USER: taiga
  POSTGRES_PASSWORD: taiga
  POSTGRES_HOST: taiga-db
  # Taiga settings
  TAIGA_SECRET_KEY: "taiga-back-secret-key"
  TAIGA_SITES_SCHEME: "http"
  TAIGA_SITES_DOMAIN: "localhost:9000"
  TAIGA_SUBPATH: "" # "" or "/subpath"
  # Email settings. Uncomment following lines and configure your SMTP server
  # EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  # DEFAULT_FROM_EMAIL: "no-reply@example.com"
  # EMAIL_USE_TLS: "False"
  # EMAIL_USE_SSL: "False"
  # EMAIL_HOST: "smtp.host.example.com"
  # EMAIL_PORT: 587
  # EMAIL_HOST_USER: "user"
  # EMAIL_HOST_PASSWORD: "password"
  # Rabbitmq settings
  # Should be the same as in taiga-async-rabbitmq and taiga-events-rabbitmq
  RABBITMQ_USER: taiga
  RABBITMQ_PASS: taiga
  # Telemetry settings
  ENABLE_TELEMETRY: "True"

x-volumes:
  &default-back-volumes
  - taiga-static-data:/taiga-back/static
  - taiga-media-data:/taiga-back/media
  # - ./config.py:/taiga-back/settings/config.py


services:
  taiga-db:
    restart: unless-stopped
    container_name: taiga-db
    image: postgres:12.3
    networks:
      - services-network
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: taiga
    volumes:
      - taiga-db-data:/var/lib/postgresql/data

  taiga-back:
    restart: unless-stopped
    container_name: taiga-back
    image: taigaio/taiga-back:latest
    networks:
      - services-network
    environment: *default-back-environment
    volumes: *default-back-volumes
    depends_on:
      - taiga-db
      - taiga-events-rabbitmq
      - taiga-async-rabbitmq

  taiga-async:
    restart: unless-stopped
    container_name: taiga-async
    image: taigaio/taiga-back:latest
    networks:
      - services-network
    entrypoint: ["/taiga-back/docker/async_entrypoint.sh"]
    environment: *default-back-environment
    volumes: *default-back-volumes
    depends_on:
      - taiga-db
      - taiga-back
      - taiga-async-rabbitmq

  taiga-async-rabbitmq:
    restart: unless-stopped
    container_name: taiga-async-rabbitmq
    image: rabbitmq:3.8-management-alpine
    networks:
      - services-network
    environment:
      RABBITMQ_ERLANG_COOKIE: secret-erlang-cookie
      RABBITMQ_DEFAULT_USER: taiga
      RABBITMQ_DEFAULT_PASS: taiga
      RABBITMQ_DEFAULT_VHOST: taiga
    volumes:
      - taiga-async-rabbitmq-data:/var/lib/rabbitmq

  taiga-front:
    restart: unless-stopped
    container_name: taiga-front
    networks:
      - services-network
    image: taigaio/taiga-front:latest
    environment:
      TAIGA_URL: "https://taiga.localhost"
      TAIGA_WEBSOCKETS_URL: "ws://taiga.localhost"
      TAIGA_SUBPATH: "" # "" or "/subpath"
    # volumes:
    #   - ./conf.json:/usr/share/nginx/html/conf.json

  taiga-events:
    restart: unless-stopped
    container_name: taiga-events
    image: taigaio/taiga-events:latest
    networks:
      - services-network
    environment:
      RABBITMQ_USER: taiga
      RABBITMQ_PASS: taiga
      TAIGA_SECRET_KEY: "taiga-back-secret-key"
    depends_on:
      - taiga-events-rabbitmq

  taiga-events-rabbitmq:
    container_name: taiga-events-rabbitmq
    restart: unless-stopped
    image: rabbitmq:3.8-management-alpine
    networks:
      - services-network
    environment:
      RABBITMQ_ERLANG_COOKIE: secret-erlang-cookie
      RABBITMQ_DEFAULT_USER: taiga
      RABBITMQ_DEFAULT_PASS: taiga
      RABBITMQ_DEFAULT_VHOST: taiga
    volumes:
      - taiga-events-rabbitmq-data:/var/lib/rabbitmq

  taiga-protected:
    restart: unless-stopped
    container_name: taiga-protected
    image: taigaio/taiga-protected:latest
    networks:
      - services-network
    environment:
      MAX_AGE: 360
      SECRET_KEY: "taiga-back-secret-key"

  taiga-gateway:
    restart: unless-stopped
    image: nginx:1.19-alpine
    networks:
      - services-network
    container_name: taiga
    volumes:
      - ./taiga-gateway/taiga.conf:/etc/nginx/conf.d/default.conf
      - taiga-static-data:/taiga/static
      - taiga-media-data:/taiga/media
    depends_on:
      - taiga-front
      - taiga-back
      - taiga-events

