Bo Burnham:
  Inside:
    cover_art: https://m.media-amazon.com/images/I/61BT8gBPPSS._SS500_.jpg
    That Funny Feeling:
      url: https://www.youtube.com/watch?v=ObOqq1knVxs
Bos Burnham:
  Inside:
    cover_art: https://m.media-amazon.com/images/I/61BT8gBPPSS._SS500_.jpg
    That Funny Feeling:
      url: https://www.youtube.com/watch?v=ObOqq1knVxs
