#!/bin/bash

weekamount=$(($1 -1))
echo Amount of milestones to be created: $weekamount
projectid=$2
echo Project ID: $projectid

while [ $weekamount -ge 0 ]; do
    echo $weekamount

    let nextweek=weekamount+1
    title=$(date +'Week %V' -d "$nextweek week")
    start_date=$(date +%F -d "monday $weekamount week")
    due_date=$(date +%F -d "sunday $nextweek week")
   
    data="title=$title&start_date=$start_date&due_date=$due_date"
    echo $data
    curl -Lk -X POST -d "$data" -H @gitlab-token "https://gitlab.localhost/api/v4/projects/$projectid/milestones"
    let weekamount=weekamount-1
done
